name : CI Security Pipeline

on :
    push :
        branches : [main]
    pull_request :
        branches : [main]
permissions:
    contents: read
jobs :
    security-checks:
        runs-on: ubuntu-latest
        steps:
          - name : Checkout code
            uses : actions/checkout@v4
            with:
                fetch-depth: 0
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
                node-version: '20'
          - name: Install dependencies
            run: npm install
          - name: Run npm audit
            run: npm audit --audit-level=high
          - name: Run Gitleaks secret scan
            uses: gitleaks/gitleaks-action@v2
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Generate SBOM
            uses: anchore/sbom-action@v0
            with:
                format: cyclonedx-json
                output-file: sbom.json
          - name: Scan SBOM with Grype
            uses: anchore/scan-action@v6
            with:
              sbom: sbom.json
              fail-build: true
              severity-cutoff: high